# Generated by Django 5.1 on 2024-09-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment_delete_payments'),
        ('users', '0004_create_moderators_group'),
    ]

    operations = [
    ]
