# Generated by Django 5.1 on 2024-09-03 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_options_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
